### ISSUE TITLE
运行demo.py的时候，出现报错。。。

### ISSUE THREAD

**Issue by mings1212** [courao/ocr.pytorch#10]
C:\Users\Administrator\AppData\Local\Programs\Python\Python37\python.exe C:/Users/Administrator/Desktop/pytorch/ocr.pytorch-master/demo.py
Traceback (most recent call last):
./test_result\test_images\t1.txt
  File "C:/Users/Administrator/Desktop/pytorch/ocr.pytorch-master/demo.py", line 29, in <module>
    txt_f = open(txt_file, 'w')
FileNotFoundError: [Errno 2] No such file or directory: './test_result\\test_images\\t1.txt'

Process finished with exit code 1

我看到demo.py运行之后会清空掉test_result文件夹里的内容，然后就报这个错误。。。
求up主帮忙看一下。。

**Comment by courao** [comment]
你再跑一次试试？这个我在windows下与遇到过类似的问题，是因为代码中会test_result文件夹然后重新生成一个文件夹test_result，但是后面如果写入的时候系统没反应过来，没有及时更新目录没找到test_result文件夹就会报这个错

**Comment by mings1212** [comment]
非常感谢，问题得以解决！

**Comment by canberkakartuna** [comment]
I am using Windows and I encountered the same problem. Could you please help me out.

FileNotFoundError: [Errno 2] No such file or directory: './test_result\\test_images\\t1.txt'

**Comment by yongen9696** [comment]
> I am using Windows and I encountered the same problem. Could you please help me out.
> 
> FileNotFoundError: [Errno 2] No such file or directory: './test_result\test_images\t1.txt'

Please comment out the following lines (19-20) in demo.py:
```
  if os.path.exists(result_dir):
      shutil.rmtree(result_dir)
```
