### ISSUE TITLE
对一段代码不解，特来与up主交流

### ISSUE THREAD

**Issue by mings1212** [courao/ocr.pytorch#12]
ocr.pytorch/detect/ctpn_predict.py第43行，
`image = image.astype(np.float32) - config.IMAGE_MEAN`
对这一步的操作的意义（是减均值吗？），以及config.IMAGE_MEAN取值的依据不懂。。。
我是刚入门机器视觉，问题也比较小白，有劳up主了。。

**Comment by courao** [comment]
是的，config.IMAGE_MEAN中的三个值分别是blue green red三个通道的图像均值，在代码里的值是从IMAGENET数据集上一个均值，比较有代表性，其实也可以直接取128简单粗暴一点，其实差异不大

**Comment by mings1212** [comment]
多谢解答，好棒！
