### ISSUE TITLE
麻烦问一下模型对图片有尺寸要求吗？我识别了一张表格，只能识别出两行，我认为可能是图片太长了？

### ISSUE THREAD

**Issue by wangguanhua** [courao/ocr.pytorch#14]

**Comment by courao** [comment]
可以放一下图片吗，对于h*w的图片来说，如果h比w大很多的话需要调整ctpn_predict.py中的height值，调大一些就行。

**Comment by wangguanhua** [comment]
![1](https://user-images.githubusercontent.com/25172472/69605557-63c2ca80-105b-11ea-982b-6af06afa7b1f.png)
这一种的，1653*2337

**Comment by courao** [comment]
这种比较长的图片可以调整ctpn_predict.py中的20行 height值，我测试了一下在调到2000左右效果还可以，你可以试着再调整一下，当然代价是处理所需的时间会长很多，你也试着可以调整19行的prob_thresh，把检测阈值降低一点也能调高检测效果

**Comment by wangguanhua** [comment]
好的，我去试试，麻烦你了
