### ISSUE TITLE
Upload pretrained models to other host

### ISSUE THREAD

**Issue by Johndirr** [courao/ocr.pytorch#16]
Can you please upload the pretrained models to another site than pan.baidu? Most non chinese users can't download from there.
Maybe https://www.mediafire.com/, https://www.4shared.com/, https://mega.nz/, googledrive or https://zippyshare.com/
Thank you very much.

**Comment by courao** [comment]
Thank you for your advice, and I'm currently put my pretrained model onto google driver(link can be found on homepage).
But as recognition model are mainly trained with a lot of Chinese data and a few English data, I not sure if it can behave well.

**Comment by Johndirr** [comment]
Thank you. Ill see how good this performs on english text.

**Comment by fcakyon** [comment]
@Johndirr how good does it perform on non-Chinese words?
