### ISSUE TITLE
CRNN

### ISSUE THREAD

**Issue by 897486562** [courao/ocr.pytorch#22]
请问，送入crnn网络的数据如果高度大于32，训练crnn时将数据预先resize成高度32，对ctpn检测出的文本，也resize成32的然后再送入训练好的crnn模型，这样子的话是不是针对高度大于32的文本也可以正常进行识别呢？

**Comment by courao** [comment]
嗯，是这个道理，代码里面已经对过高或者过低的文本进行等比例缩放所以可以直接用
