### ISSUE TITLE
运行demo出错

### ISSUE THREAD

**Issue by vcbeaut** [courao/ocr.pytorch#23]
![111](https://user-images.githubusercontent.com/22236673/73149277-7c9f3900-40fb-11ea-840b-5bd668408fd1.png)

**Comment by vcbeaut** [comment]
@courao 怎么会跟caffe有关呢？

**Comment by courao** [comment]
跟caffe没有关系 应该是你路径或者你的python环境有问题， from detect.ctpn_predict import **** 应该是这个ocr.pytorch文件夹下的，而看你的截图是你系统目录自带的detect 而这个detect似乎和caffe有关，建议建个虚拟环境吧

**Comment by vcbeaut** [comment]
我是用的conda 虚拟环境

**Comment by courao** [comment]
那不应该跟/usr/local/caffe/python/detect有关联的

**Comment by vcbeaut** [comment]
确实是detect文件夹和caffe的库detect冲突了，我改成detect_文件夹就可以了，谢谢
