### ISSUE TITLE
能不能给出训练部分的代码？

### ISSUE THREAD

**Issue by kUhNCwlVbsWXClUR** [courao/ocr.pytorch#3]
作者您好，我试了一个你给出的模型，效果挺不错的，非常谢谢您给出的代码
期待您的字符识别训练的代码和数据集

**Comment by Crescentz** [comment]
请问这个问题解决了么。怎么关闭了

**Comment by courao** [comment]
由于最近几个月在实习暂时没有整理好代码，9月实习结束我会整理一下代码解决一些目前存在的问题。 @yugengde @Crescentz

**Comment by kUhNCwlVbsWXClUR** [comment]
> 请问这个问题解决了么。怎么关闭了

没有呢，一直等作者的回复，等着等着就关了

**Comment by kUhNCwlVbsWXClUR** [comment]
> 由于最近几个月在实习暂时没有整理好代码，9月实习结束我会整理一下代码解决一些目前存在的问题。 @yugengde @Crescentz
嗯嗯，好的，谢谢啦！
