### ISSUE TITLE
空格不识别

### ISSUE THREAD

**Issue by Crescentz** [courao/ocr.pytorch#4]
![image](https://user-images.githubusercontent.com/35165563/62179513-749a5280-b37f-11e9-84f1-f3f8d1934c6b.png)

**Comment by Crescentz** [comment]
空格识别不出来，文本都事大写字母是啥情况

**Comment by zhs108** [comment]
@Crescentz 空格本身就是不用识别的。整体的流程是：先检测出来每个单词，然后对每个单词进行识别。如果想要空格，可以改一下demo.py的第34行改一下，比如：
            print(result[key][1] + ‘ ’)

**Comment by courao** [comment]
@Crescentz 目前的版本是有这个问题，由于最近几个月在实习暂时没有处理这个问题，9月实习结束我会重新整理代码处理这个问题，顺便也会放出解决空格和英文大小写的版本。

**Comment by Crescentz** [comment]
@zhs108 @courao 谢谢
